apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert
  namespace: blue
spec:
  secretName: cloudgeeks
  issuerRef:
    name: issuer
    kind: Issuer
  dnsNames:
    - blue.cloudgeeks.tk

  # kubectl get certs -n app
  # kubectl describe certs/cert -n app  