# secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: cloudgeeks
  namespace: blue
type: kubernetes.io/tls
stringData:
  tls.key: ""
  tls.crt: ""




#  tls.crt:  # content of ca.crt (converted to base64)
#  tls.key:  # content of ca.key (converted to base64)

 # https://superuser.com/questions/1225134/why-does-the-base64-of-a-string-contain-n

  # file base64 encoding
  # base64 -w 0 cloudgeeks.tk.crt > 1.crt
  # base64 -w 0 cloudgeeks.tk.key > 1.key

  # string base64 encoding
  # echo -n "apfjxkic-omyuobwd339805ak:60a06cd2ddfad610b9490d359d605407" | base64 -w 0  
