apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert
  namespace: app
spec:
  secretName: ssl
  issuerRef:
    name: issuer
    kind: Issuer
  dnsNames:
    - app.cloudgeeks.tk

  # kubectl get certs -n app
  # kubectl describe certs/cert -n app  